"""create room_members

Revision ID: d0c308f91283
Revises: fc6c29bfccb3
Create Date: 2026-08-24 10:35:54.896402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c308f91283'
down_revision: Union[str, Sequence[str], None] = 'fc6c29bfccb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_members',
    sa.Column('room_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_members_room_id_rooms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_room_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id', name=op.f('pk_room_members'))
    )
    op.create_index(op.f('ix_room_members_user_id'), 'room_members', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_room_members_user_id'), table_name='room_members')
    op.drop_table('room_members')
    # ### end Alembic commands ###
